apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    matadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: danitakeshi/projeto-database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolice: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name: mysql-dados
          mounthPath: /var/lib/mysql/
      volumes:
      - name: mysql-dados
        persistentVolumeClaim:
          claimName: mysql-dados
---
apiVersion: v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: danitakeshi/projeto-backend:1.0
        imagePullPolice: Always
        ports:
        - containerPort: 80